jobs:
  deploy:
    strategy:
      matrix:
        node-version: [14.x, 16.x]
    name: Deploy to EC2
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the files
      uses: actions/checkout@v2
    - name: Set up Node ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test
    - name: Deploy to Server 1
      uses: easingthemes/ssh-deploy@main
      env:
        SOURCE: "./dist/"
        SSH_PRIVATE_KEY: ${{secrets.EC2_SSH_KEY}}
        REMOTE_HOST: ${{secrets.HOST_DNS}}
        REMOTE_USER: ${{secrets.USERNAME}}
        TARGET: ${{secrets.TARGET_DIR}}
    - name: executing remote ssh commands using ssh key
      uses: appleboy/ssh-action@master
      with:
        host: ${{secrets.HOST_DNS}}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.EC2_SSH_KEY}}
        script: |
          sh /home/${{secrets.USERNAME}}/web/deploy.sh
          exit